# -*- coding: utf-8 -*-
"""knn.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxTr_sJQqJNCvVlW1i4rsYnqumZfErc-
"""

import pickle
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Load the Iris dataset
iris = load_iris()
X, y = iris.data, iris.target

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the KNN model
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Save the trained model
with open("knn_model.pkl", "wb") as model_file:
    pickle.dump(knn, model_file)

print("Model training complete! Model saved as knn_model.pkl.")

